// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDojW7xWkshZ1UVD2bb-yvr5uj8LXJ6Hdc',
    appId: '1:870161096208:android:61171d950f6d83e85c7495',
    messagingSenderId: '870161096208',
    projectId: 'proyecto-final-2-167bf',
    storageBucket: 'proyecto-final-2-167bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQo0bUHqRAL0sZ6WFyPHf1PeCfdupgVlQ',
    appId: '1:870161096208:ios:a420096602373e355c7495',
    messagingSenderId: '870161096208',
    projectId: 'proyecto-final-2-167bf',
    storageBucket: 'proyecto-final-2-167bf.firebasestorage.app',
    iosClientId: '870161096208-te3o60tmsm66nlcpkleqh8cfshsrdsse.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebaTecnica1',
  );
}
